### ISSUE TITLE
ScalabilityUIPanel.cpp: ResolutionQuality is set differently

### ISSUE THREAD

**Issue by dff180** [Teddy0/ScalabilityUIPlugin#1]
Hi, thanks for providing this helpful tool.
Just took a quick look at the code on GitHub and noticed that in

ScalabilityUIPanel.cpp

you set ScreenPercentage in 

  OnGroupQualityLevelChanged()

to

```
CachedQualityLevels.ResolutionQuality * 1.35f
```

while in 

  OnResolutionScaleChanged()

it's set to

```
CachedQualityLevels.ResolutionQuality
```

Not sure if this is maybe a bug.

Cheers,
dfff180

**Comment by Teddy0** [comment]
That's most definitely a bug, well spotted!

**Comment by Teddy0** [comment]
Fixed!
